### ISSUE TITLE
Kubernetes Pods created but not services

### ISSUE THREAD

**Issue by vkris6** [zalando/zalenium#320]
Zalenium Image Version(s):  latest
Docker Version:  Docker version 1.12.6, build d9ad3fc
OS: coreos 1520.8.0
Kubernetes Version: 1.6.1, with one node.

Am using Kubernetes on Core OS and I see the attached errors. Pods get created but not the services. Could you please advise. I don't see any errors that could be due to kubernetes. But see the below errors in the Hub logs. When I delete the latest images from kubernetes node and try again its works fine.

**Observation below:**
1) Pods get created but not services.
2) when I delete the images from the box and create 10 max sessios, everything works fine.
3) when trying to create 50 max sessions, only 24 services created but all the pods were created.

Debug Logs:
===========
[failed_logs.txt](https://github.com/zalando/zalenium/files/1472635/failed_logs.txt)

Kubernetes yaml:
=============
[test-1.txt](https://github.com/zalando/zalenium/files/1472692/test-1.txt)

**Comment by diemol** [comment]
Hi @vkris6,

Thanks for providing the logs, it actually helps to understand better.

Looks like the main issue is that the node is actually created properly, and it wants to register itself to the hub, but somehow the hub cannot reach the node even if the IP is there.

For example:
```
22:36:54.990 DEBUG - Pod zalenium-test-1-40001-37twv, IP -> null 
...
22:36:57.994 DEBUG - Pod zalenium-test-1-40001-37twv, IP -> null
...
22:37:01.025 DEBUG - Pod zalenium-test-1-40001-37twv, IP -> null
...
22:37:01.103 DEBUG - getting the following registration request  : {"class":"org.openqa.grid.common.RegistrationRequest","name":null,"description":null,"configuration":{"remoteHost":"http://10.2.26.4:40001","hubHost":"10.2.26.3","hubPort":4445,"id":"http://10.2.26.4:40001","capabilities":[{"acceptSslCerts":true,"browserName":"chrome","maxInstances":1,"platform":"LINUX","resolution":"1440x810","screen-resolution":"1440x810","screenResolution":"1440x810","seleniumProtocol":"WebDriver","tz":"Europe/Berlin","version":"62.0.3202.94"}],"downPollingLimit":2,"hub":"http://10.2.26.3:4445/grid/register","nodePolling":114000,"nodeStatusCheckTimeout":5000,"proxy":"de.zalando.ep.zalenium.proxy.DockerSeleniumRemoteProxy","register":true,"registerCycle":0,"unregisterIfStillDownAfter":2500,"cleanUpCycle":5000,"custom":{},"host":"10.2.26.4","maxSession":1,"servlets":[],"withoutServlets":[],"browserTimeout":0,"debug":false,"jettyMaxThreads":null,"log":null,"port":40001,"role":"node","timeout":1800,"enablePassThrough":true}}
22:37:01.107 DEBUG - Using class de.zalando.ep.zalenium.proxy.DockerSeleniumRemoteProxy
2017-11-14 22:37:01 WARN  HttpChannel:517 - /grid/register
java.security.InvalidParameterException: Error: Unable to locate pod by ip address, registration will fail
	at org.openqa.grid.internal.BaseRemoteProxy.getNewInstance(BaseRemoteProxy.java:363)
	at org.openqa.grid.web.servlet.RegistrationServlet.process(RegistrationServlet.java:104)
	at org.openqa.grid.web.servlet.RegistrationServlet.doPost(RegistrationServlet.java:71)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
...
22:37:04.030 DEBUG - Pod zalenium-test-1-40001-37twv, IP -> null
...
22:37:07.034 DEBUG - Pod zalenium-test-1-40001-37twv, IP -> 10.2.26.4
```

The `IP -> null` messages, is when Zalenium is keeping track of the created pod, and waiting for it to have an IP to query its health. The IP is queried via the Kubernetes API. If you check the log events, the IP cannot be retrieved, but the node is already registering to the hub and then the hub cannot reach the node via the provided IP. At the end of the log messages, the IP is retrieved but it seems that it is quite late.

For me, it looks like the node is ready with its IP, but this info is not yet spread in the internal cluster DNS (just speculating here). This might be related to #275.

In the end, the node cannot register itself, and it ends up being not used and in a "zombie" state. Usually when you restart Zalenium, things work fine, which is what I think you mean by "When I delete the latest images from kubernetes node and try again its works fine.".

I plan to take a look at this soon because we need to improve the way the nodes register, making that part more resilient to these type of errors. If you have any more info that might help, that would be highly appreciated.

**Comment by vkris6** [comment]
Hi @diemol ,

Initially i thought this could be the problem with internal cluster DNS, but when i delete the docker images dosel/zalenium and elgalu/selenium from my local so that kubernetes downloads it again. In this case for the first time i don't see this issue.  Seems to be like some form of caching either docker or kubernetes. Do you think the same?

I started using this a month back and I had never encountered this before. from past 1 week am seeing this issue. i switched back to 3.6.0a and the same issue exists, I have to delete the locally downloaded images for everything to work fine again.

Am currently running more tests and try to get as much information possible.

**Comment by diemol** [comment]
Thats new @vkris6, first time I hear that behaviour. 

But still, I think that if the node tried to register again, it would work, making that part more robust.

Thanks advance for the info you could get.

**Comment by pearj** [comment]
In #341 I removed all references to services, so maybe this problem doesn't matter anymore?

**Comment by vkris6** [comment]
I was using 4vCPU box initially, where we had kubernetes cluster, everything was working fine.
we upgraded the same machine to 36vCPU and started testing, this is where i see the problem.
Now I have downgraded the same machine back to 4vCPU, and the problem does not exists anymore.
Its weird, but this is what i have observed.

**Comment by pearj** [comment]
Ahh I read the comments more carefully and I see it’s a registration problem. So removing services probably won’t fix that. It sounds more like a symptom than a cause. Yesterday when I was spinning 25 nodes up and down on my laptop, sometimes some pods Vnc connections wouldn’t work, maybe it’s related, not sure. But I didn’t bother to investigate.

**Comment by diemol** [comment]
Hi,

A release was made moments ago https://github.com/zalando/zalenium/releases/tag/3.8.1c
In this release, the nodes will try to register again whenever the initial registration was not successful, and this should fix the problem described above.

@vkris6 could you please give it a try and report back?

**Comment by vkris6** [comment]
Hi @diemol 

This works fine now. But 2 issues i observe in 3.8.1c

1) Kubernetes service is only created for hub.
2) I only have config to start chrome containers but i still see firefox containers coming up.

**Comment by diemol** [comment]
Hi @vkris6, thanks for reporting back!

Here my answers to your comments:
 >Kubernetes service is only created for hub.

Yes, this is the new behaviour since @pearj helped us to proxy the LivePreview via nginx, which was the only reason why we needed to create services for each new node. (The same change will follow soon for docker as well).

>I only have config to start chrome containers but i still see firefox containers coming up.

That's ok, since a few releases ago, the created nodes are able to process tests for both browsers (only one at a time of course). This was made to simplify the configuration and performance is not affected, now the user only needs to think about containers and not a given amount for Firefox and for Chrome. You can use the new parameter `--desiredContainers` instead of the other two old ones.

I'll close the since the behaviour has improved. Feel free to reopen in case this happens again.
