### ISSUE TITLE
Zalenium nodes not registering

### ISSUE THREAD

**Issue by hjacobs** [zalando/zalenium#577]
I run the curl command from the README and Docker containers start, but throw errors and Grid Console is empty.

```
curl -sSL https://raw.githubusercontent.com/dosel/t/i/p | env USE_NET_HOST=true bash -s start
```

```
docker ps
CONTAINER ID        IMAGE                                                 COMMAND                  CREATED             STATUS              PORTS                                            NAMES
b8a01eceead0        elgalu/selenium:latest                                "entry.sh"               8 minutes ago       Up 8 minutes                                                         zalenium_s6NeYe
35d7143705b9        elgalu/selenium:latest                                "entry.sh"               8 minutes ago       Up 8 minutes                                                         zalenium_2Xmrjp
c3da9527c3fc        dosel/zalenium:latest                                 "entry.sh start --ti…"   8 minutes ago       Up 8 minutes                                                         zalenium

```

```
$ docker logs b8a01eceead0
--LOG 14:29:33:323532388 Stopping supervisord to support docker restart...
-- INFO: Docker Img. Version: 3.11.0-252
-- INFO: Chrome..... Version: 66.0.3359.181
-- INFO: Firefox.... Version: 60.0
-- INFO: Using Selenium.....: 
-- INFO: Possible free DISPLAY=:35
***************** BEGIN: Data Processing Agreement *****************
By using this software you agree that the following non-PII
(non personally identifiable information) data will be collected,
processed and used by Docker-selenium for the purpose of improving
our test infrastructure tools. Anonymisation with respect of the IP
address means that only the first two octets of the IP address are
collected. See the complete license at:
https://github.com/elgalu/docker-selenium/blob/master/LICENSE.md
****************** END: Data Processing Agreement ******************
supervisord --version=4.0.0.dev0
2018-05-16 14:29:34,731 INFO Included extra file "/etc/supervisor/conf.d/novnc.conf" during parsing
2018-05-16 14:29:34,731 INFO Included extra file "/etc/supervisor/conf.d/selenium-hub.conf" during parsing
2018-05-16 14:29:34,731 INFO Included extra file "/etc/supervisor/conf.d/selenium-multinode.conf" during parsing
2018-05-16 14:29:34,731 INFO Included extra file "/etc/supervisor/conf.d/selenium-node-chrome.conf" during parsing
2018-05-16 14:29:34,731 INFO Included extra file "/etc/supervisor/conf.d/selenium-node-firefox.conf" during parsing
2018-05-16 14:29:34,732 INFO Included extra file "/etc/supervisor/conf.d/video-rec.conf" during parsing
2018-05-16 14:29:34,732 INFO Included extra file "/etc/supervisor/conf.d/vnc.conf" during parsing
2018-05-16 14:29:34,732 INFO Included extra file "/etc/supervisor/conf.d/xmanager.conf" during parsing
2018-05-16 14:29:34,732 INFO Included extra file "/etc/supervisor/conf.d/xterm.conf" during parsing
2018-05-16 14:29:34,746 INFO RPC interface 'supervisor' initialized
2018-05-16 14:29:34,746 INFO RPC interface 'supervisor' initialized
2018-05-16 14:29:34,747 INFO supervisord started with pid 163
2018-05-16 14:29:35,749 INFO spawned: 'xmanager' with pid 166
2018-05-16 14:29:35,750 INFO spawned: 'vnc' with pid 167
2018-05-16 14:29:35,752 INFO spawned: 'novnc' with pid 168
2018-05-16 14:29:35,754 INFO spawned: 'selenium-multinode' with pid 169
2018-05-16 14:29:35,758 INFO spawned: 'xterm' with pid 171
2018-05-16 14:29:35,766 INFO success: xterm entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2018-05-16 14:29:36,950 INFO exited: vnc (exit status 0; not expected)
2018-05-16 14:29:36,972 INFO exited: novnc (exit status 133; not expected)
2018-05-16 14:29:37,534 INFO exited: selenium-multinode (exit status 0; not expected)
2018-05-16 14:29:38,536 INFO success: xmanager entered RUNNING state, process has stayed up for > than 2 seconds (startsecs)
2018-05-16 14:29:38,537 INFO spawned: 'vnc' with pid 332
2018-05-16 14:29:38,540 INFO spawned: 'novnc' with pid 333
2018-05-16 14:29:38,542 INFO spawned: 'selenium-multinode' with pid 334
2018-05-16 14:29:39,262 INFO exited: selenium-multinode (exit status 0; not expected)
2018-05-16 14:29:39,597 INFO exited: vnc (exit status 0; not expected)
2018-05-16 14:29:39,665 INFO exited: novnc (exit status 133; not expected)
2018-05-16 14:29:41,669 INFO spawned: 'vnc' with pid 446
2018-05-16 14:29:41,670 INFO spawned: 'novnc' with pid 447
2018-05-16 14:29:41,672 INFO spawned: 'selenium-multinode' with pid 448
2018-05-16 14:29:42,619 INFO exited: selenium-multinode (exit status 0; not expected)
2018-05-16 14:29:42,667 INFO gave up: selenium-multinode entered FATAL state, too many start retries too quickly
2018-05-16 14:29:42,755 INFO exited: vnc (exit status 0; not expected)
2018-05-16 14:29:42,771 INFO exited: novnc (exit status 133; not expected)
2018-05-16 14:29:45,775 INFO spawned: 'vnc' with pid 554
2018-05-16 14:29:45,777 INFO spawned: 'novnc' with pid 555
2018-05-16 14:29:46,829 INFO exited: vnc (exit status 0; not expected)
2018-05-16 14:29:46,873 INFO gave up: vnc entered FATAL state, too many start retries too quickly
2018-05-16 14:29:46,874 INFO exited: novnc (exit status 133; not expected)
2018-05-16 14:29:46,874 INFO gave up: novnc entered FATAL state, too many start retries too quickly
```
```
docker logs c3da9527c3fc
14:38:42.430 [qtp672746064-15] WARN  d.z.e.z.c.DockerContainerClient - No container id for zalenium - 127.0.0.1, can't register.
14:38:42.430 [Thread-39] INFO  d.z.e.z.registry.ZaleniumRegistry - Registered a node http://127.0.0.1:40000
14:38:42.436 [Thread-39] WARN  d.z.e.z.proxy.AutoStartProxySet - Registered (or re-registered) a container null http://127.0.0.1:40000 that is not tracked by the pool, marking down.
14:38:42.436 [Thread-39] INFO  d.z.e.z.p.DockerSeleniumRemoteProxy - null Marking node down.
14:39:02.596 [qtp672746064-15] WARN  d.z.e.z.c.DockerContainerClient - No container id for zalenium - 127.0.0.1, can't register.
14:39:02.597 [Thread-40] INFO  d.z.e.z.registry.ZaleniumRegistry - Registered a node http://127.0.0.1:40000
14:39:02.599 [Thread-40] WARN  d.z.e.z.proxy.AutoStartProxySet - Registered (or re-registered) a container null http://127.0.0.1:40000 that is not tracked by the pool, marking down.
14:39:02.599 [Thread-40] INFO  d.z.e.z.p.DockerSeleniumRemoteProxy - null Marking node down.
```

I don't know what's going on, but my automated UI tests are not working anymore (that's why I started debugging locally, see above), the error from my automated (Python) test is:

```
10:33:59 AMselenium.common.exceptions.WebDriverException: Message: Error forwarding the new session Request timed out waiting for a node to become available.

10:33:59 AMStacktrace:

10:33:59 AMat org.openqa.grid.web.servlet.handler.RequestHandler.process (RequestHandler.java:118)

10:33:59 AMat org.openqa.grid.web.servlet.DriverServlet.process (DriverServlet.java:86)

10:33:59 AMat org.openqa.grid.web.servlet.DriverServlet.doPost (DriverServlet.java:70)

10:33:59 AMat javax.servlet.http.HttpServlet.service (HttpServlet.java:707)

10:33:59 AMat javax.servlet.http.HttpServlet.service (HttpServlet.java:790)

10:33:59 AMat org.seleniumhq.jetty9.servlet.ServletHolder.handle (ServletHolder.java:860)

10:33:59 AMat org.seleniumhq.jetty9.servlet.ServletHandler$CachedChain.doFilter (ServletHandler.java:1650)

10:33:59 AMat io.prometheus.client.filter.MetricsFilter.doFilter (MetricsFilter.java:170)

10:33:59 AMat org.seleniumhq.jetty9.servlet.ServletHandler$CachedChain.doFilter (ServletHandler.java:1637)

10:33:59 AMat org.seleniumhq.jetty9.servlet.ServletHandler.doHandle (ServletHandler.java:533)

10:33:59 AMat org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle (ScopedHandler.java:188)

10:33:59 AMat org.seleniumhq.jetty9.server.session.SessionHandler.doHandle (SessionHandler.java:1595)

10:33:59 AMat org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle (ScopedHandler.java:188)

10:33:59 AMat org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle (ContextHandler.java:1253)

10:33:59 AMat org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope (ScopedHandler.java:168)

10:33:59 AMat org.seleniumhq.jetty9.servlet.ServletHandler.doScope (ServletHandler.java:473)

10:33:59 AMat org.seleniumhq.jetty9.server.session.SessionHandler.doScope (SessionHandler.java:1564)

10:33:59 AMat org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope (ScopedHandler.java:166)

10:33:59 AMat org.seleniumhq.jetty9.server.handler.ContextHandler.doScope (ContextHandler.java:1155)

10:33:59 AMat org.seleniumhq.jetty9.server.handler.ScopedHandler.handle (ScopedHandler.java:141)

10:33:59 AMat org.seleniumhq.jetty9.server.handler.StatisticsHandler.handle (StatisticsHandler.java:169)

10:33:59 AMat org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle (HandlerWrapper.java:132)

10:33:59 AMat org.seleniumhq.jetty9.server.Server.handle (Server.java:530)

10:33:59 AMat org.seleniumhq.jetty9.server.HttpChannel.handle (HttpChannel.java:347)

10:33:59 AMat org.seleniumhq.jetty9.server.HttpConnection.onFillable (HttpConnection.java:256)

10:33:59 AMat org.seleniumhq.jetty9.io.AbstractConnection$ReadCallback.succeeded (AbstractConnection.java:279)

10:33:59 AMat org.seleniumhq.jetty9.io.FillInterest.fillable (FillInterest.java:102)

10:33:59 AMat org.seleniumhq.jetty9.io.ChannelEndPoint$2.run (ChannelEndPoint.java:124)

10:33:59 AMat org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.doProduce (EatWhatYouKill.java:247)

10:33:59 AMat org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.produce (EatWhatYouKill.java:140)

10:33:59 AMat org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.run (EatWhatYouKill.java:131)

10:33:59 AMat org.seleniumhq.jetty9.util.thread.ReservedThreadExecutor$ReservedThread.run (ReservedThreadExecutor.java:382)

10:33:59 AMat org.seleniumhq.jetty9.util.thread.QueuedThreadPool.runJob (QueuedThreadPool.java:708)

10:33:59 AMat org.seleniumhq.jetty9.util.thread.QueuedThreadPool$2.run (QueuedThreadPool.java:626)

10:33:59 AMat java.lang.Thread.run (Thread.java:748)

10:33:59 AM

10:33:59 AM----------------------------------------------------------------------

10:33:59 AMRan 1 test in 600.359s

10:33:59 AM

10:33:59 AMFAILED (errors=1)
```

**Comment by pearj** [comment]
You can't use --net=host anymore, a recent restructure now expects every container to have a separate IP address.
This is the same as #567

**Comment by pearj** [comment]
@diemol I added a pull request on the dosel side to fail if that option is used. But maybe it should be removed entirely. 
I wonder if the docker container can figure out the network mode and prevent from starting?

**Comment by diemol** [comment]
It is a common use case to run a docker-selenium or Zalenium container locally in order to test an application running on localhost (someone who wants to run tests against uncommitted code for example). 
In Linux it is very simple with `net=host`, so even if we remove that option, we should still document how to do that with the recent changes.

**Comment by hjacobs** [comment]
@pearj @diemol thanks for the quick answers, can we change the default to not use `latest` Docker images? I think my problem was that "I did not change anything" and it broke because the Docker images (`latest`) got updated and support for `--net=host` was removed without me having any chance to influence/react. I think this is not a very nice behaviour, especially for automated CI/CD pipelines where stuff starts to break "out of nothing" (and users like me first assume it's a code change in their app).

**Comment by hjacobs** [comment]
I could get it to work again (without net=host), but it was quite painful as I had to use the `docker0` IP (172.17.0.1) in my Python webapp test (which does not run in Docker) to be able to access my Python test app from Zalenium (Docker containers).

**Comment by diemol** [comment]
It is possible to start with a previous version by executing the command like this:

`curl -sSL https://raw.githubusercontent.com/dosel/t/i/p | bash -s 3.11.0e start`

(3.11.0e was the tag before the changes were made)

We were checking the needed changes, and we'll bring back support for `net=host` in the next release. 

In general, with the changes Selenium is going through towards the W3C standard, is recommendable to run with a fix tag or start the one line script with the version specified.

**Comment by hjacobs** [comment]
@diemol thanks, but this would still leave me with the risk of having a dependency to the non-versioned script `https://raw.githubusercontent.com/dosel/t/i/p`.

**Comment by diemol** [comment]
I think that having the script in the same repo makes a lot of sense. I don't remember exactly why we left it in a different one, do you remember why @elgalu? I guess in the beginning the script was more like a nice helper and we didn't think it would be highly used.

Would be cool if someone finds the time to send a PR and move the script here, perhaps rework it?

For now, the support for `net=host` will be included in the next release (3.12.0a).

Thanks for reporting this @hjacobs!

**Comment by hjacobs** [comment]
@diemol sounds good, thanks!

**Comment by hjacobs** [comment]
Now something is breaking again (I did not change the setup, but I see that one of the Docker images was updated) :disappointed: 

```
lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 193, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Session [ff3106f02d08d18739a6974ce32dd077] was terminated due to ORPHAN
Stacktrace:
    at org.openqa.grid.internal.ActiveTestSessions.getExistingSession (ActiveTestSessions.java:115)
    at de.zalando.ep.zalenium.registry.ZaleniumRegistry.getExistingSession (ZaleniumRegistry.java:399)
    at org.openqa.grid.web.servlet.handler.RequestHandler.getSession (RequestHandler.java:241)
    at org.openqa.grid.web.servlet.handler.RequestHandler.process (RequestHandler.java:123)
    at org.openqa.grid.web.servlet.DriverServlet.process (DriverServlet.java:86)
    at org.openqa.grid.web.servlet.DriverServlet.doPost (DriverServlet.java:70)
    at javax.servlet.http.HttpServlet.service (HttpServlet.java:707)

**Comment by hjacobs** [comment]
OK, this time it might be my app's fault --- I have to check..

**Comment by diemol** [comment]
One of the docker images was updated since Firefox 60.0.1 was released today.
Please also double check that the Python bindings are 3.11.0 (current version of Zalenium)

**Comment by diemol** [comment]
Hi,

We just released 3.12.0a, which brings back support for `net=host`, please have a look.

@scherniavsky, about LTS support... That sounds tricky because Selenium has many moving parts: the browser, the browser drivers, the bindings themselves. To have LTS support we would need to double check every single component, and maybe also add elgalu/selenium as well... This sounds like an endless task.

In case you want to have some sort of extra checks, I could recommend to have the image internally mirrored, and whenever there is a release, you could pull it from Docker Hub, test it with the regular use cases you might have, and if everything goes fine, push it to the internal registry.

**Comment by kkargatane** [comment]
Hi! I'm still seeing this issue on version 3.12.0b when running in --net=host mode. 

This is the command I'm running:
```
docker run --rm -ti --privileged --net=host --name zalenium -v /var/run/docker.sock:/var/run/docker.sock -v /tmp/videos:/home/seluser/videos dosel/zalenium:3.12.0b start --sendAnonymousUsageInfo false --desiredContainers 1
```

This is the log output:
```
16:58:21.173 [qtp1622458036-20] WARN  d.z.e.z.c.DockerContainerClient - No container id for zalenium - 127.0.0.1, can't register.
16:58:21.175 [Thread-10] INFO  d.z.e.z.registry.ZaleniumRegistry - Registered a node http://127.0.0.1:40000
16:58:21.178 [Thread-10] WARN  d.z.e.z.proxy.AutoStartProxySet - Registered (or re-registered) a container null http://127.0.0.1:40000 that is not tracked by the pool, marking down.
16:58:21.178 [Thread-10] INFO  d.z.e.z.p.DockerSeleniumRemoteProxy - null Marking node down.
16:58:21.788 [AutoStartProxyPoolPoller] INFO  d.z.e.z.proxy.AutoStartProxySet - Container zalenium_0jCWbi started after 4176.
16:58:45.361 [qtp1622458036-15] WARN  d.z.e.z.c.DockerContainerClient - No container id for zalenium - 127.0.0.1, can't register.
16:58:45.362 [Thread-11] INFO  d.z.e.z.registry.ZaleniumRegistry - Registered a node http://127.0.0.1:40000
16:58:45.362 [Thread-11] WARN  d.z.e.z.proxy.AutoStartProxySet - Registered (or re-registered) a container null http://127.0.0.1:40000 that is not tracked by the pool, marking down.
16:58:45.362 [Thread-11] INFO  d.z.e.z.p.DockerSeleniumRemoteProxy - null Marking node down.
16:59:09.477 [qtp1622458036-20] WARN  d.z.e.z.c.DockerContainerClient - No container id for zalenium - 127.0.0.1, can't register.
16:59:09.478 [Thread-12] INFO  d.z.e.z.registry.ZaleniumRegistry - Registered a node http://127.0.0.1:40000
16:59:09.479 [Thread-12] WARN  d.z.e.z.proxy.AutoStartProxySet - Registered (or re-registered) a container null http://127.0.0.1:40000 that is not tracked by the pool, marking down.
16:59:09.479 [Thread-12] INFO  d.z.e.z.p.DockerSeleniumRemoteProxy - null Marking node down.
16:59:33.619 [qtp1622458036-16] WARN  d.z.e.z.c.DockerContainerClient - No container id for zalenium - 127.0.0.1, can't register.
16:59:33.620 [Thread-13] INFO  d.z.e.z.registry.ZaleniumRegistry - Registered a node http://127.0.0.1:40000
16:59:33.620 [Thread-13] WARN  d.z.e.z.proxy.AutoStartProxySet - Registered (or re-registered) a container null http://127.0.0.1:40000 that is not tracked by the pool, marking down.
16:59:33.620 [Thread-13] INFO  d.z.e.z.p.DockerSeleniumRemoteProxy - null Marking node down.
```
