### ISSUE TITLE
DockerContainerClient cannot find the containers during registration when using net=host option

### ISSUE THREAD

**Issue by MilindThakur** [zalando/zalenium#632]
Seem the issue is same as #577. The other issue has been closed, but the last post on the thread shows error with build 3.12.0b (and the --net=host capability was re-added in 3.12.0a)

Staring the zalenium container with '--net=host' option fails to register the node container. Zalenium tries continuously but fails and marks the node down.

This was working a while ago, around build 3.11.0e.

I have been using this to run tests against an application that run locally.

Zalenium Image Version(s):  
3.12.0e
Docker Version:  
Docker version 17.09.1-ce, build 19e2cf6
OS: 
Ubuntu 16.04.1
Docker Command to start Zalenium: As per the doc
```
docker run --rm -ti --name zalenium --net=host \
      -v /var/run/docker.sock:/var/run/docker.sock \
      -v /tmp/videos:/home/seluser/videos \
      --privileged dosel/zalenium start
```

## Expected Behavior -
Should be able to access the application running on localhost.

## Actual Behavior -
Fails to register the node container onto the zalenium grid.

## Logs -
```
$ docker run --rm -ti --name zalenium --net=host       -v /var/run/docker.sock:/var/run/docker.sock       -v /tmp/videos:/home/seluser/videos       --privileged dosel/zalenium start --desiredContainers 1
Docker version 17.09.1-ce, build 19e2cf6
-- LOG 21:59:58:482237414 Ensuring docker works...
-- LOG 21:59:58:529640502 Ensuring no stale Zalenium related containers are still around...
-- LOG 21:59:58:546800710 Ensuring docker-selenium is available...
haveged: haveged starting up
Copying files for Dashboard...
Starting Nginx reverse proxy...
Starting Selenium Hub...
...21:59:59.155 [main] INFO  o.o.grid.selenium.GridLauncherV3 - Selenium build info: version: '3.12.0', revision: 'unknown'
21:59:59.158 [main] INFO  o.o.grid.selenium.GridLauncherV3 - Launching Selenium Grid hub on port 4445
.21:59:59.366 [AutoStartProxyPoolPoller] INFO  d.z.e.z.proxy.AutoStartProxySet - Starting poller.
21:59:59.367 [AutoStartProxyPoolPoller] INFO  d.z.e.z.proxy.AutoStartProxySet - Autostarting container, because 0 is less than min 1
.21:59:59.706 [main] INFO  d.z.ep.zalenium.aspect.HubAspect - Registering custom Zalenium servlets
.21:59:59.771 [main] INFO  org.openqa.grid.web.Hub - Selenium Grid hub is up and running
21:59:59.771 [main] INFO  org.openqa.grid.web.Hub - Nodes should register to http://172.19.0.1:4445/grid/register/
21:59:59.771 [main] INFO  org.openqa.grid.web.Hub - Clients should connect to http://172.19.0.1:4445/wd/hub
Selenium Hub started!
Sauce Labs not enabled...
Browser Stack not enabled...
TestingBot not enabled...
Zalenium is now ready!
*************************************** Data Processing Agreement ***************************************
By using this software you agree that the following non-PII (non personally identifiable information)
data will be collected, processed and used by Zalando SE for the purpose of improving our test
infrastructure tools. Anonymisation with respect of the IP address means that only the first two octets
of the IP address are collected.

See the complete license at https://github.com/zalando/zalenium/blob/master/LICENSE.md
*************************************** Data Processing Agreement ***************************************
22:00:01.480 [AutoStartProxyPoolPoller] INFO  d.z.e.z.p.DockeredSeleniumStarter - Created container [zalenium_UhUNTP] with dimensions [(1920, 1080)] and tz [sun.util.calendar.ZoneInfo[id="Europe/Berlin",offset=3600000,dstSavings=3600000,useDaylight=true,transitions=143,lastRule=java.util.SimpleTimeZone[id=Europe/Berlin,offset=3600000,dstSavings=3600000,useDaylight=true,startYear=0,startMode=2,startMonth=2,startDay=-1,startDayOfWeek=1,startTime=3600000,startTimeMode=2,endMode=2,endMonth=9,endDay=-1,endDayOfWeek=1,endTime=3600000,endTimeMode=2]]].
22:00:01.481 [AutoStartProxyPoolPoller] INFO  d.z.e.z.proxy.AutoStartProxySet - Created ContainerCreationStatus [isCreated=true, containerName=zalenium_UhUNTP, containerId=ca9e313846eb4826a07c20c7daa75fe4ca398ff2e77bf6a8eb2b10972239b0f7, nodePort=40000].
_22:00:04.420 [qtp1870209957-17] WARN  d.z.e.z.c.DockerContainerClient - No container id for zalenium - 127.0.0.1, can't register._
22:00:04.421 [Thread-13] INFO  d.z.e.z.registry.ZaleniumRegistry - Registered a node http://127.0.0.1:40000
22:00:04.423 [Thread-13] WARN  d.z.e.z.proxy.AutoStartProxySet - Registered (or re-registered) a container null http://127.0.0.1:40000 that is not tracked by the pool, marking down.
22:00:04.423 [Thread-13] INFO  d.z.e.z.p.DockerSeleniumRemoteProxy - null Marking node down.
22:00:04.585 [AutoStartProxyPoolPoller] INFO  d.z.e.z.proxy.AutoStartProxySet - Container zalenium_UhUNTP started after 3104.
22:00:21.561 [qtp1870209957-19] WARN  d.z.e.z.c.DockerContainerClient - No container id for zalenium - 127.0.0.1, can't register.
22:00:21.561 [Thread-14] INFO  d.z.e.z.registry.ZaleniumRegistry - Registered a node http://127.0.0.1:40000
22:00:21.561 [Thread-14] WARN  d.z.e.z.proxy.AutoStartProxySet - Registered (or re-registered) a container null http://127.0.0.1:40000 that is not tracked by the pool, marking down.
22:00:21.561 [Thread-14] INFO  d.z.e.z.p.DockerSeleniumRemoteProxy - null Marking node down.
^CTrapped SIGTERM/SIGINT so shutting down Zalenium gracefully...
Stopping Hub...
-- LOG 22:00:24:389805136 Ensuring no stale Zalenium related containers are still around...
Removing exited docker-selenium containers...
ca9e313846eb
*************************************** Data Processing Agreement ***************************************
By using this software you agree that the following non-PII (non personally identifiable information)
data will be collected, processed and used by Zalando SE for the purpose of improving our test
infrastructure tools. Anonymisation with respect of the IP address means that only the first two octets
of the IP address are collected.

See the complete license at https://github.com/zalando/zalenium/blob/master/LICENSE.md
*************************************** Data Processing Agreement ***************************************
```

**Comment by MilindThakur** [comment]
Just wondering if you have any comments on this? Continue to exist on the latest zalenium:3.13.0a

**Comment by pearj** [comment]
Looks like your problem is related to: `WARN  d.z.e.z.c.DockerContainerClient - No container id for zalenium - 127.0.0.1, can't register._` although I never run the docker version of zalenium, so not sure how it's supposed to work in that instance.

**Comment by diemol** [comment]
Fixed via the referenced commit, a new release will be done soon with this fix included.

**Comment by MilindThakur** [comment]
Thanks, is working back again on zalenium 3.14.0c.

**Comment by happyali** [comment]
Zalenium release was 3.141.59z

I am still facing the same issue in win 10

**Comment by diemol** [comment]
`net=host` does not work in Windows, only in Linux. It is a Docker limitation, not Zalenium's.
