### ISSUE TITLE
Zalenium occasionally hangs

### ISSUE THREAD

**Issue by kendalsickels-wf** [zalando/zalenium#663]
**Please make sure that you provide enough information for us to help you with this issue. Thank you!**

Zalenium Image Version(s):  

```dosel/zalenium:3.12.0g```

Docker Version:  

```18.03.1-ce```

If using docker-compose, version:  

```1.21.2```

OS: 

```Linux```

Docker Command to start Zalenium:  

```docker-compose --project-name $_projectName -f $composePath up -d zalenium```

compose file:
```
version: '3.6'

zalenium:
    image: "dosel/zalenium:3.12.0g"
    hostname: zalenium
    privileged: true
    tty: true
    volumes:
      - ${SKYNET_TESTING_PATH}/videos:/home/seluser/videos
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - ${SKYNET_TESTING_PATH}/exports:/tmp/node/home/seluser/exports
      - ${SKYNET_TESTING_PATH}/test/functional/web:/tmp/node/home/seluser/imports
    # un-comment out the items below when running zalenium locally in skynet-cli to watch the tests
#    ports:
#      - 4444:4444
    command: >
      start --desiredContainers 10
            --maxDockerSeleniumContainers 20
            --screenWidth 1440 --screenHeight 900
            --timeZone "America/Chicago"
            --videoRecordingEnabled true
            --sauceLabsEnabled true
            --browserStackEnabled false
            --testingBotEnabled false
            --startTunnel false
            --maxTestSessions 2
            --seleniumImageName elgalu/selenium:3.12.0-p10
    environment:
      SAUCE_USERNAME: $SAUCE_USERNAME
      SAUCE_ACCESS_KEY: $SAUCE_ACCESS_KEY
```

## Expected Behavior -
Zalenium is able to use and teardown nodes as needed until test run is complete

## Actual Behavior -
Occasionally zalenium hangs and nodes are either not being reused or are not being torn down when they've been used. Have not been able to catch this locally only on an Amazon ec2 c5.9xlarge instance (36 CPUs and 72GBs RAM) running 91 tests (6 running on SauceLabs) on a concurrency of 10.

Logs when zalenium is hanging:

```
INFO  o.o.g.w.s.handler.RequestHandler - Error forwarding the new session Request timed out waiting for a node to become available.

java.util.concurrent.TimeoutException: Request timed out waiting for a node to become available.
stdout:

org.openqa.grid.web.servlet.handler.RequestHandler.waitForSessionBound(RequestHandler.java:197)
org.openqa.grid.web.servlet.handler.RequestHandler.process(RequestHandler.java:112)
org.openqa.grid.web.servlet.DriverServlet.process(DriverServlet.java:86)
org.openqa.grid.web.servlet.DriverServlet.doPost(DriverServlet.java:70)
javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
org.seleniumhq.jetty9.servlet.ServletHolder.handle(ServletHolder.java:860)
org.seleniumhq.jetty9.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1650)
io.prometheus.client.filter.MetricsFilter.doFilter(MetricsFilter.java:170)
org.seleniumhq.jetty9.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
org.seleniumhq.jetty9.servlet.ServletHandler.doHandle(ServletHandler.java:533)
org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
org.seleniumhq.jetty9.security.SecurityHandler.handle(SecurityHandler.java:548)
org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:190)
org.seleniumhq.jetty9.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
org.seleniumhq.jetty9.servlet.ServletHandler.doScope(ServletHandler.java:473)
org.seleniumhq.jetty9.server.session.SessionHandler.doScope(SessionHandler.java:1564)
org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
org.seleniumhq.jetty9.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
org.seleniumhq.jetty9.server.handler.StatisticsHandler.handle(StatisticsHandler.java:169)
org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
org.seleniumhq.jetty9.server.Server.handle(Server.java:530)
org.seleniumhq.jetty9.server.HttpChannel.handle(HttpChannel.java:347)
org.seleniumhq.jetty9.server.HttpConnection.onFillable(HttpConnection.java:256)
org.seleniumhq.jetty9.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
org.seleniumhq.jetty9.io.FillInterest.fillable(FillInterest.java:102)
org.seleniumhq.jetty9.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:247)
org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:140)
org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
org.seleniumhq.jetty9.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:382)
org.seleniumhq.jetty9.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:708)
org.seleniumhq.jetty9.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:626)
java.lang.Thread.run(Thread.java:748)
```

**Comment by mrbar42** [comment]
I had a similar issue which turned out to be stale browser nodes.

because browser nodes are not terminated consistently when the parent does, there is a child nodes "leakage".
the problem arose (in my case) when these stale nodes reached `--maxDockerSeleniumContainers` and then session requests to zalenium stalled indefinitely

i resolved it be manually cleaning nodes by name before starting a new composition and after the composition is closed (ugly but working).

```sh
# this command will close all zalenium child nodes under this project name
# note that zalenium container name is assumed to be "zalenium"
COMPOSE_PROJECT_NAME="my-compo"
# clean before starting
docker kill $(docker ps | grep "${COMPOSE_PROJECT_NAME}_zalenium_1_") 2>&1 || true
# run composition
docker-compose -p "$COMPOSE_PROJECT_NAME" up
# clean again after close
docker kill $(docker ps | grep "${COMPOSE_PROJECT_NAME}_zalenium_1_") 2>&1 || true
``

**Comment by pearj** [comment]
We’ve noticed the occasional stale nodes too in kubernetes. Unfortunately I haven’t done proper investigations when it’s failed and I’ve just restarted zalenium. Would be good to get some detailed state information about what docker thinks and what zalenium thinks. When it hangs for me the live preview shows broken containers. It’s like the containers are gone but zalenium thinks they are still there. Not sure what happens if you kill a container in docker/kubernetes maybe the grid doesn’t automatically remove it.

**Comment by pearj** [comment]
@mrbar42 The kubernetes version of zalenium automatically deletes all pods on start and shutdown, so it wouldn't suffer from your exact problem. But have you seen a cause for the stale nodes?

**Comment by mrbar42** [comment]
I wasn't able to nail down the cause thus far

**Comment by snovikov** [comment]
We had a similar issue while running zalenium in Kubernetes. Problem was solved by giving more resources to pods, e.g. setting limits higher.

**Comment by kendalsickels-wf** [comment]
Is there a way for me to bump the resource limits for the docker-selenium nodes that get started by Zalenium?

**Comment by diemol** [comment]
Is this still valid, there were some improvements that should mitigate this.
If it is still valid, could you please provide a test suite using any Selenium official binding to reproduce the issue?

**Comment by kendalsickels-wf** [comment]
@diemol which improvements were those? I can bump our Zalenium version today but want to be sure I'm not missing any new settings additions/changes that would help us out.

**Comment by diemol** [comment]
@kendalsickels-wf sorry for the late reply.
We have released a new version with more internal improvements https://github.com/zalando/zalenium/releases/tag/3.141.59d

Some of them are:
- The logging should be more simple to understand, which will be helpful when issues are reported.
- The list of proxies are now handled with a [ConcurrentHashMap](https://github.com/zalando/zalenium/commit/f19f4c16d2ba986b4e519daae4752cf066836742#diff-adb0eee832169eabaa7bddcb7385d6f7R65), which has better performance over a CopyOnWriteArrayList. 
- There was a bug where more containers than the allowed ones were being created, which was [fixed](https://github.com/zalando/zalenium/commit/5fc5b530e4d34bd2e81779a6688a787773e19f53#diff-8a47361134ca2b4b48d239dae1c8954aR293) in 3.14.0c.

Now, about
>Is there a way for me to bump the resource limits for the docker-selenium nodes that get started by Zalenium?

This is not really possible when using docker because the containers have no limits configured, so the real limits are the resources available in the machine itself. In Kubernetes is quite different because depending on the limits you set, potentially the cluster can allocate that to the pods. 

The error you mentioned above:
>Request timed out waiting for a node to become available.

This means that the test request was in the queue for a long time, and then the `newSessionWaitTimeout` kicked in, which currently is 10 minutes (600000 ms). You can have a look at #784 to see how to set it up. The reason for the error could be because too many tests request were sent and too few containers were running. This timeout also counts for the tests that are waiting for a slot in a cloud provider.

If you can, please have a look at the release I mentioned above and give us some feedback.

**Comment by kendalsickels-wf** [comment]
@diemol I was able to update Zalenium and docker-selenium versions today to latest still hitting occasional failures where everything hangs and I see this in the logs:

`ERROR o.o.g.w.s.handler.RequestHandler - cannot forward the request unexpected end of stream on Connection{172.19.0.33:40026, proxy=DIRECT hostAddress=/172.19.0.33:40026 cipherSuite=none protocol=http/1.1}
0m 2018-12-08T03:23:00.287359598Z java.io.IOException: unexpected end of stream on Connection{172.19.0.33:40026, proxy=DIRECT hostAddress=/172.19.0.33:40026 cipherSuite=none protocol=http/1.1}
[0m 2018-12-08T03:23:00.288429330Z 	at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:208)
[0m 2018-12-08T03:23:00.288451346Z 	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:88)
[0m 2018-12-08T03:23:00.288455330Z 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
[0m 2018-12-08T03:23:00.288458076Z 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
[0m 2018-12-08T03:23:00.288460748Z 	at org.openqa.selenium.remote.internal.OkHttpClient$Factory$1.lambda$createClient$1(OkHttpClient.java:152)
[0m 2018-12-08T03:23:00.288463208Z 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
[0m 2018-12-08T03:23:00.288465734Z 	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
[0m 2018-12-08T03:23:00.288468220Z 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
[0m 2018-12-08T03:23:00.288470573Z 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
[0m 2018-12-08T03:23:00.288472888Z 	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
[0m 2018-12-08T03:23:00.288475192Z 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
[0m 2018-12-08T03:23:00.288477533Z 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
[0m 2018-12-08T03:23:00.288479760Z 	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
[0m 2018-12-08T03:23:00.288481994Z 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
[0m 2018-12-08T03:23:00.288484587Z 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
[0m 2018-12-08T03:23:00.288487144Z 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
[0m 2018-12-08T03:23:00.288489385Z 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
[0m 2018-12-08T03:23:00.288491603Z 	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
[0m 2018-12-08T03:23:00.288493847Z 	at okhttp3.RealCall.execute(RealCall.java:77)
[0m 2018-12-08T03:23:00.288498667Z 	at org.openqa.selenium.remote.internal.OkHttpClient.execute(OkHttpClient.java:103)
[0m 2018-12-08T03:23:00.288501106Z 	at org.openqa.grid.internal.TestSession.sendRequestToNode(TestSession.java:422)
[0m 2018-12-08T03:23:00.288511825Z 	at org.openqa.grid.internal.TestSession.forward(TestSession.java:229)
[0m 2018-12-08T03:23:00.288514379Z 	at org.openqa.grid.web.servlet.handler.RequestHandler.forwardRequest(RequestHandler.java:99)
[0m 2018-12-08T03:23:00.288516692Z 	at org.openqa.grid.web.servlet.handler.RequestHandler.process(RequestHandler.java:133)
[0m 2018-12-08T03:23:00.288518973Z 	at org.openqa.grid.web.servlet.DriverServlet.process(DriverServlet.java:85)
[0m 2018-12-08T03:23:00.288521216Z 	at org.openqa.grid.web.servlet.DriverServlet.doGet(DriverServlet.java:63)
[0m 2018-12-08T03:23:00.288523416Z 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
[0m 2018-12-08T03:23:00.288525629Z 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
[0m 2018-12-08T03:23:00.288527807Z 	at org.seleniumhq.jetty9.servlet.ServletHolder.handle(ServletHolder.java:865)
[0m 2018-12-08T03:23:00.288530073Z 	at org.seleniumhq.jetty9.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1655)
[0m 2018-12-08T03:23:00.288532351Z 	at io.prometheus.client.filter.MetricsFilter.doFilter(MetricsFilter.java:170)
[0m 2018-12-08T03:23:00.288534582Z 	at org.seleniumhq.jetty9.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
[0m 2018-12-08T03:23:00.288536854Z 	at org.seleniumhq.jetty9.servlet.ServletHandler.doHandle(ServletHandler.java:533)
[0m 2018-12-08T03:23:00.288539082Z 	at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
[0m 2018-12-08T03:23:00.288541351Z 	at org.seleniumhq.jetty9.security.SecurityHandler.handle(SecurityHandler.java:548)
[0m 2018-12-08T03:23:00.288543686Z 	at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
[0m 2018-12-08T03:23:00.288545928Z 	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
[0m 2018-12-08T03:23:00.288548178Z 	at org.seleniumhq.jetty9.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
[0m 2018-12-08T03:23:00.288550432Z 	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
[0m 2018-12-08T03:23:00.288552776Z 	at org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle(ContextHandler.java:1340)
[0m 2018-12-08T03:23:00.288554998Z 	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
[0m 2018-12-08T03:23:00.288557236Z 	at org.seleniumhq.jetty9.servlet.ServletHandler.doScope(ServletHandler.java:473)
[0m 2018-12-08T03:23:00.288559581Z 	at org.seleniumhq.jetty9.server.session.SessionHandler.doScope(SessionHandler.java:1564)
[0m 2018-12-08T03:23:00.288562457Z 	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
[0m 2018-12-08T03:23:00.288564762Z 	at org.seleniumhq.jetty9.server.handler.ContextHandler.doScope(ContextHandler.java:1242)
[0m 2018-12-08T03:23:00.288567107Z 	at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
[0m 2018-12-08T03:23:00.288571868Z 	at org.seleniumhq.jetty9.server.handler.StatisticsHandler.handle(StatisticsHandler.java:174)
[0m 2018-12-08T03:23:00.288574280Z 	at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
[0m 2018-12-08T03:23:00.288576661Z 	at org.seleniumhq.jetty9.server.Server.handle(Server.java:503)
[0m 2018-12-08T03:23:00.288578930Z 	at org.seleniumhq.jetty9.server.HttpChannel.handle(HttpChannel.java:364)
[0m 2018-12-08T03:23:00.288581191Z 	at org.seleniumhq.jetty9.server.HttpConnection.onFillable(HttpConnection.java:260)
[0m 2018-12-08T03:23:00.288583451Z 	at org.seleniumhq.jetty9.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
[0m 2018-12-08T03:23:00.288585742Z 	at org.seleniumhq.jetty9.io.FillInterest.fillable(FillInterest.java:103)
[0m 2018-12-08T03:23:00.288587962Z 	at org.seleniumhq.jetty9.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
[0m 2018-12-08T03:23:00.288590455Z 	at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
[0m 2018-12-08T03:23:00.288593669Z 	at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
[0m 2018-12-08T03:23:00.288596827Z 	at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
[0m 2018-12-08T03:23:00.288600235Z 	at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
[0m 2018-12-08T03:23:00.288603668Z 	at org.seleniumhq.jetty9.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
[0m 2018-12-08T03:23:00.288607062Z 	at org.seleniumhq.jetty9.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
[0m 2018-12-08T03:23:00.288610315Z 	at org.seleniumhq.jetty9.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
[0m 2018-12-08T03:23:00.288613729Z 	at java.lang.Thread.run(Thread.java:748)
[0m 2018-12-08T03:23:00.288616849Z Caused by: java.io.EOFException: \n not found: limit=0 content=?
[0m 2018-12-08T03:23:00.288620624Z 	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:237)
[0m 2018-12-08T03:23:00.288623604Z 	at okhttp3.internal.http1.Http1Codec.readHeaderLine(Http1Codec.java:215)
[0m 2018-12-08T03:23:00.288626506Z 	at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:189)
[0m 2018-12-08T03:23:00.288629380Z 	... 61 common frames omitted`

Not sure if setting `newSessionWaitTimeout` to be something other than the default would help.  We currently are running only 10 tests concurrently and allowing 20 containers.  But open to any suggestions you might have.

**Comment by diemol** [comment]
@kendalsickels-wf the message from the last comment should be fixed in the latest [release](https://github.com/zalando/zalenium/releases/tag/3.141.59e)

About this [comment](https://github.com/zalando/zalenium/issues/663#issuecomment-445430404), is there a way you can help me to reproduce this one?

**Comment by diemol** [comment]
@kendalsickels-wf we just merged a fix that solves the initial "hanging" situation (since I was able to reproduce it by coincidence).

About this [stacktrace](https://github.com/zalando/zalenium/issues/663#issuecomment-445430404), it is the same issue as #783, so we will follow up there.

**Comment by kendalsickels-wf** [comment]
@diemol reaching out on this old issue as we are still getting what appears to be a node registration/zalenium hang up. Verified we still see this after updating to `dosel/zalenium:3.141.59n` and `elgalu/selenium:3.141.59-p12`.

Zalenium container logs don't give me any insight into the issue outside of still encountering https://github.com/zalando/zalenium/issues/783 but don't believe that to be the cause for this hang up. I've been able to get the test run to complete when it encounters this issue and it appears that after a point in time every test times out trying to connect a new driver session to nodes.

We are running 10 tests concurrently with a `maxDockerSeleniumContainers=15` and `maxTestSessions=1`. Is there any way to get additional logging outside of the Zalenium container logs? Perhaps logging for each node that starts up?
